baseurl: ""
exclude: ["node_modules"]
include:
  - assets/icons/*.svg
  - assets/images/**/*

# ========================
# DEFAULTS (for single-page folders)
# ========================
defaults:
  - scope:
      path: ""          # Applies to all files in root folders
      type: "pages"     # Only affects standalone pages (not collections)
    values:
      layout: "default" # Optional: Set your default layout

# ========================
# PERMALINKS (for prettier URLs)
# ========================
permalink: pretty
